[["Both teams played hard.", "Rasheed Wallace", "2003"],
["Not a game! Not a game... practice...", "Allen Iverson", "2002"],
["That’s why they're fans and we're NBA players.", "Bonzi Wells", "2002"],
["I just didn't want a white guy guarding me, because it's disrespect to my game.", "Larry Bird", "2004"],
["I love Sam Cassell. He's a great guy, but he does look like E.T.", "Charles Barkley", "2010"],
["Nothing easy.", "Zaza Pachulia", "2012"],
["What a pathetic play from a pathetic human being.", "Bill Walton (on Larry Johnson)", "1999"],
["This Portland team is nothing more than a band of pranksters.", "Bill Walton", "2003"],
["It's always frustrating when you get down 40 points.", "Nazr Mohammed", "2008"],
["Violence is never the answer, but sometimes it is.", "Matt Barnes on Derek Fisher", "2016"],
["If you don't want to get hacked then work on your fucking free throws.", "Kevin Durant", "2015"],
["Don't even put me and dude in the same breath.", "Kobe Bryant on Ray Allen", "2006"],
["I mean, I never heard someone say, I'm going to Cleveland on vacation", "Joakim Noah", "2010"],
["There will always be haters, that’s just the way it is. Hating dudes marry hating women and have hating ass kids", "Evan Turner", "2013"],
["I'm not going to be one of those guys that's just out here chasing that ring", "David West", "2014"],
["I make love to pressure.", "Stephen Jackson", "2004"],
["Did this dude just did this?", "John Starks", "2010"],
["Smush Parker is the worst. He shouldn't have been in the NBA but we were too cheap to pay for a point guard. So we let him walk on.", "Kobe Bryant", "2012"],
["You got guys out there playing high every night. You got 60% of your league on marijuana. What can you do?", "Charles Oakley", "2001"],
["I would carry a razor blade and cut myself to get a free timeout", "Jeff Van Gundy", "2014"],
["Dick Vitale is pole riding the skin off the heat", "Andre Iguodala", "2011"],
["First time at jack in the box, they got funnel cakes. Hyped.", "Wesley Matthews", "2011"],
["Men lie, women lie, buckets dont.", "Dion Waiters", "2014"],
["Yesterday we celebrated Sir Isaac Newton's discovery of gravity. Today, Fabricio Oberto is defying it.", "Bill Walton", "2009"],
["Who can stop Keith Closs? He's the best player in the NBA.", "Bill Walton", "1998"],
["The Magic are on the clock with the first pick. If they're smart, they take Emeka Okafor. If they're dumb, they take Howard. It's that simple.", "Bill Simmons", "2004"],
["I'm the most unracist person around.", "Don Nelson", ""],
["I'm all about the fried chicken.", "Rick Mahorn", ""]]