# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-30 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='recent_notes',
            field=models.CharField(default='No recent notes.', max_length=2000),
        ),
        migrations.AddField(
            model_name='player',
            name='roto_id',
            field=models.IntegerField(default=0),
        ),
    ]
