# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-05 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_player_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=150)),
                ('person', models.CharField(max_length=30)),
                ('year', models.CharField(blank=True, max_length=4, null=True)),
            ],
        ),
    ]
