# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-12 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0005_player_statlines'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='rostered',
            field=models.BooleanField(default=True),
        ),
    ]
