# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-23 01:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0006_player_rostered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='rostered',
        ),
        migrations.AddField(
            model_name='player',
            name='retired',
            field=models.BooleanField(default=False),
        ),
    ]
