# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 20:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('tipoff', models.CharField(blank=True, max_length=8, null=True)),
                ('home_team', models.CharField(choices=[('ATL', 'Atlanta Hawks'), ('BRK', 'Brooklyn Nets'), ('BOS', 'Boston Celtics'), ('CHO', 'Charlotte Hornets'), ('CHI', 'Chicago Bulls'), ('CLE', 'Cleveland Cavaliers'), ('DAL', 'Dallas Mavericks'), ('DEN', 'Denver Nuggets'), ('DET', 'Detroit Pistons'), ('GSW', 'Golden State Warriors'), ('HOU', 'Houston Rockets'), ('IND', 'Indiana Pacers'), ('LAC', 'Los Angeles Clippers'), ('LAL', 'Los Angeles Lakers'), ('MEM', 'Memphis Grizzlies'), ('MIA', 'Miami Heat'), ('MIN', 'Minnesota Timberwolves'), ('MIL', 'Milwaukee Bucks'), ('NOP', 'New Orleans Pelicans'), ('NYK', 'New York Knicks'), ('OKC', 'Oklahoma City Thunder'), ('ORL', 'Orlando Magic'), ('PHI', 'Philadelphia 76ers'), ('PHO', 'Phoenix Suns'), ('POR', 'Portland TrailBlazers'), ('SAS', 'San Antonio Spurs'), ('SAC', 'Sacramento Kings'), ('TOR', 'Toronto Raptors'), ('UTA', 'Utah Jazz'), ('WAS', 'Washington Wizards'), ('FA', 'Free Agent')], max_length=25, verbose_name='Home Team')),
                ('away_team', models.CharField(choices=[('ATL', 'Atlanta Hawks'), ('BRK', 'Brooklyn Nets'), ('BOS', 'Boston Celtics'), ('CHO', 'Charlotte Hornets'), ('CHI', 'Chicago Bulls'), ('CLE', 'Cleveland Cavaliers'), ('DAL', 'Dallas Mavericks'), ('DEN', 'Denver Nuggets'), ('DET', 'Detroit Pistons'), ('GSW', 'Golden State Warriors'), ('HOU', 'Houston Rockets'), ('IND', 'Indiana Pacers'), ('LAC', 'Los Angeles Clippers'), ('LAL', 'Los Angeles Lakers'), ('MEM', 'Memphis Grizzlies'), ('MIA', 'Miami Heat'), ('MIN', 'Minnesota Timberwolves'), ('MIL', 'Milwaukee Bucks'), ('NOP', 'New Orleans Pelicans'), ('NYK', 'New York Knicks'), ('OKC', 'Oklahoma City Thunder'), ('ORL', 'Orlando Magic'), ('PHI', 'Philadelphia 76ers'), ('PHO', 'Phoenix Suns'), ('POR', 'Portland TrailBlazers'), ('SAS', 'San Antonio Spurs'), ('SAC', 'Sacramento Kings'), ('TOR', 'Toronto Raptors'), ('UTA', 'Utah Jazz'), ('WAS', 'Washington Wizards'), ('FA', 'Free Agent')], max_length=25, verbose_name='Away Team')),
                ('home_points', models.IntegerField(default=0)),
                ('away_points', models.IntegerField(default=0)),
                ('boxscore_link', models.URLField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(choices=[('2014-15', '2014-15'), ('2015-16', '2015-16'), ('2016-17', '2016-17')], default='2015-16', max_length=10, verbose_name='Season')),
            ],
        ),
        migrations.CreateModel(
            name='StatLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mp', models.CharField(blank=True, max_length=5, null=True)),
                ('fgm', models.IntegerField(default=0)),
                ('fga', models.IntegerField(default=0)),
                ('ftm', models.IntegerField(default=0)),
                ('fta', models.IntegerField(default=0)),
                ('threesm', models.IntegerField(default=0)),
                ('threesa', models.IntegerField(default=0)),
                ('orbs', models.IntegerField(default=0)),
                ('drbs', models.IntegerField(default=0)),
                ('trbs', models.IntegerField(default=0)),
                ('asts', models.IntegerField(default=0)),
                ('stls', models.IntegerField(default=0)),
                ('blks', models.IntegerField(default=0)),
                ('tos', models.IntegerField(default=0)),
                ('pfs', models.IntegerField(default=0)),
                ('pts', models.IntegerField(default=0)),
                ('added_to_player', models.BooleanField(default=False)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.Game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.Player')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.Season'),
        ),
        migrations.AddField(
            model_name='game',
            name='stat_lines',
            field=models.ManyToManyField(through='schedule.StatLine', to='players.Player'),
        ),
    ]
