# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 21:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='stat_lines',
            new_name='statlines',
        ),
    ]
