# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-31 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_auto_20160624_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='away_points',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='home_points',
            field=models.IntegerField(null=True),
        ),
    ]
