# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-22 13:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0003_team'),
        ('schedule', '0005_matchup'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchup',
            name='league',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='leagues.League'),
            preserve_default=False,
        ),
    ]
