# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-11 22:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0007_auto_20161208_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchup',
            name='away_points',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='matchup',
            name='home_points',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='statline',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sls', to='schedule.Game'),
        ),
    ]
