# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-14 22:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0008_auto_20161211_2211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchup',
            name='away_team',
        ),
        migrations.RemoveField(
            model_name='matchup',
            name='home_team',
        ),
        migrations.RemoveField(
            model_name='matchup',
            name='league',
        ),
        migrations.DeleteModel(
            name='Matchup',
        ),
    ]
