# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-01-02 18:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0009_auto_20161214_2248'),
        ('schedule', '0007_auto_20180102_1718'),
    ]

    operations = [
    ]
