# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-01-02 18:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0010_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statline',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='players.Player'),
        ),
    ]
