# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-12 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0004_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='roster_size',
            field=models.IntegerField(default=14),
        ),
    ]
