# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-12 15:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0005_player_statlines'),
        ('leagues', '0006_team_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='DraftPick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=1)),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picks', to='leagues.Draft')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='players.Player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leagues.Team')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
    ]
