# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-15 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0010_auto_20161215_0136'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matchup',
            old_name='away_fga',
            new_name='shome_threesm',
        ),
        migrations.RemoveField(
            model_name='matchup',
            name='away_fgm',
        ),
        migrations.RemoveField(
            model_name='matchup',
            name='away_fta',
        ),
        migrations.RemoveField(
            model_name='matchup',
            name='away_ftm',
        ),
        migrations.RemoveField(
            model_name='matchup',
            name='away_threesa',
        ),
        migrations.RemoveField(
            model_name='matchup',
            name='home_fga',
        ),
        migrations.RemoveField(
            model_name='matchup',
            name='home_fgm',
        ),
        migrations.RemoveField(
            model_name='matchup',
            name='home_fta',
        ),
        migrations.RemoveField(
            model_name='matchup',
            name='home_ftm',
        ),
        migrations.RemoveField(
            model_name='matchup',
            name='home_threesa',
        ),
        migrations.RemoveField(
            model_name='matchup',
            name='home_threesm',
        ),
        migrations.AddField(
            model_name='matchup',
            name='away_fgpct',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='matchup',
            name='away_ftpct',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='matchup',
            name='home_fgpct',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='matchup',
            name='home_ftpct',
            field=models.FloatField(default=0),
        ),
    ]
