# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-15 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0011_auto_20161215_1335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matchup',
            old_name='shome_threesm',
            new_name='away_fga',
        ),
        migrations.RemoveField(
            model_name='matchup',
            name='away_fgpct',
        ),
        migrations.RemoveField(
            model_name='matchup',
            name='away_ftpct',
        ),
        migrations.RemoveField(
            model_name='matchup',
            name='home_fgpct',
        ),
        migrations.RemoveField(
            model_name='matchup',
            name='home_ftpct',
        ),
        migrations.AddField(
            model_name='matchup',
            name='away_fgm',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matchup',
            name='away_fta',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matchup',
            name='away_ftm',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matchup',
            name='home_fga',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matchup',
            name='home_fgm',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matchup',
            name='home_fta',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matchup',
            name='home_ftm',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matchup',
            name='home_threesm',
            field=models.IntegerField(default=0),
        ),
    ]
