# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-15 17:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0012_auto_20161215_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
