# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-15 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0012_auto_20161215_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='needed_stat',
            field=models.CharField(choices=[('pts', 'points'), ('rebs', 'rebounds'), ('asts', 'assists'), ('stls', 'steals'), ('blks', 'blocks'), ('threesm', 'threesm')], default='PG', max_length=15, verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(default='Team', max_length=50),
        ),
    ]
