# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-22 21:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0013_auto_20161215_2059'),
        ('leagues', '0013_auto_20161215_1721'),
    ]

    operations = [
    ]
