# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-22 21:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0014_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='manager',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(default='Team', max_length=50),
        ),
    ]
