mascots = [
	"Abyssinians",
	"Adelie Penguins",
	"Affenpinschers",
	"Afghan Hounds",
	"African Bush Elephants",
	"African Civets",
	"African Clawed Frogs",
	"African Forest Elephants",
	"African Palm Civets",
	"African Penguins",
	"African Tree Toads",
	"African Wild Dogs",
	"Ainu Dogs",
	"Airedale Terriers",
	"Akbashs",
	"Akitas",
	"Alaskan Malamutes",
	"Albatrosss",
	"Aldabra Giant Tortoises",
	"Alligators",
	"Alpine Dachsbrackes",
	"American Bulldogs",
	"American Cocker Spaniels",
	"American Coonhounds",
	"American Eskimo Dogs",
	"American Foxhounds",
	"American Pit Bull Terriers",
	"American Staffordshire Terriers",
	"American Water Spaniels",
	"Anatolian Shepherd Dogs",
	"Angelfishs",
	"Ants",
	"Anteaters",
	"Antelopes",
	"Appenzeller Dogs",
	"Arctic Foxs",
	"Arctic Hares",
	"Arctic Wolfs",
	"Armadillos",
	"Asian Elephants",
	"Asian Giant Hornets",
	"Asian Palm Civets",
	"Asiatic Black Bears",
	"Australian Cattle Dogs",
	"Australian Kelpie Dogs",
	"Australian Mists",
	"Australian Shepherds",
	"Australian Terriers",
	"Avocets",
	"Axolotls",
	"Aye Ayes",
	"Baboons",
	"Bactrian Camels",
	"Badgers",
	"Balineses",
	"Banded Palm Civets",
	"Bandicoots",
	"Barbs",
	"Barn Owls",
	"Barnacles",
	"Barracudas",
	"Basenji Dogs",
	"Basking Sharks",
	"Basset Hounds",
	"Bats",
	"Bavarian Mountain Hounds",
	"Beagles",
	"Bears",
	"Bearded Collies",
	"Bearded Dragons",
	"Beavers",
	"Bedlington Terriers",
	"Beetles",
	"Bengal Tigers",
	"Bernese Mountain Dogs",
	"Bichon Frises",
	"Binturongs",
	"Birds",
	"Birds Of Paradises",
	"Birmans",
	"Bisons",
	"Black Bears",
	"Black Rhinoceross",
	"Black Russian Terriers",
	"Black Widow Spiders",
	"Bloodhounds",
	"Blue Lacy Dogs",
	"Blue Whales",
	"Bluetick Coonhounds",
	"Bobcats",
	"Bolognese Dogs",
	"Bombays",
	"Bongos",
	"Bonobos",
	"Boobys",
	"Border Collies",
	"Border Terriers",
	"Bornean Orang-utans",
	"Borneo Elephants",
	"Boston Terriers",
	"Bottle Nosed Dolphins",
	"Boxer Dogs",
	"Boykin Spaniels",
	"Brazilian Terriers",
	"Brown Bears",
	"Budgerigars",
	"Buffalos",
	"Bull Mastiffs",
	"Bull Sharks",
	"Bull Terriers",
	"Bulldogs",
	"Bullfrogs",
	"Bumble Bees",
	"Burmeses",
	"Burrowing Frogs",
	"Butterflys",
	"Butterfly Fishs",
	"Caimans",
	"Caiman Lizards",
	"Cairn Terriers",
	"Camels",
	"Canaan Dogs",
	"Capybaras",
	"Caracals",
	"Carolina Dogs",
	"Cassowarys",
	"Cats",
	"Caterpillars",
	"Catfishs",
	"Cavalier King Charles Spaniels",
	"Centipedes",
	"Cesky Fouseks",
	"Chameleons",
	"Chamoiss",
	"Cheetahs",
	"Chesapeake Bay Retrievers",
	"Chickens",
	"Chihuahuas",
	"Chimpanzees",
	"Chinchillas",
	"Chinese Crested Dogs",
	"Chinooks",
	"Chinstrap Penguins",
	"Chipmunks",
	"Chow Chows",
	"Cichlids",
	"Clouded Leopards",
	"Clown Fishs",
	"Clumber Spaniels",
	"Coatis",
	"Cockroachs",
	"Collared Peccarys",
	"Collies",
	"Common Buzzards",
	"Common Frogs",
	"Common Loons",
	"Common Toads",
	"Corals",
	"Cottontop Tamarins",
	"Cougars",
	"Cows",
	"Coyotes",
	"Crabs",
	"Crab-Eating Macaques",
	"Cranes",
	"Crested Penguins",
	"Crocodiles",
	"Cross River Gorillas",
	"Curly Coated Retrievers",
	"Cuscuss",
	"Cuttlefishs",
	"Dachshunds",
	"Dalmatians",
	"Darwin's Frogs",
	"Deers",
	"Desert Tortoises",
	"Deutsche Brackes",
	"Dholes",
	"Dingos",
	"Discuss",
	"Doberman Pinschers",
	"Dodos",
	"Dogs",
	"Dogo Argentinos",
	"Dogue De Bordeauxs",
	"Dolphins",
	"Donkeys",
	"Dormouses",
	"Dragonflys",
	"Drevers",
	"Ducks",
	"Dugongs",
	"Dunkers",
	"Dusky Dolphins",
	"Dwarf Crocodiles",
	"Eagles",
	"Earwigs",
	"Eastern Gorillas",
	"Eastern Lowland Gorillas",
	"Echidnas",
	"Edible Frogs",
	"Egyptian Maus",
	"Electric Eels",
	"Elephants",
	"Elephant Seals",
	"Elephant Shrews",
	"Emperor Penguins",
	"Emperor Tamarins",
	"Emus",
	"English Cocker Spaniels",
	"English Shepherds",
	"English Springer Spaniels",
	"Entlebucher Mountain Dogs",
	"Epagneul Pont Audemers",
	"Eskimo Dogs",
	"Estrela Mountain Dogs",
	"Falcons",
	"Fennec Foxs",
	"Ferrets",
	"Field Spaniels",
	"Fin Whales",
	"Finnish Spitzs",
	"Fire-Bellied Toads",
	"Fishs",
	"Fishing Cats",
	"Flamingos",
	"Flat Coat Retrievers",
	"Flounders",
	"Flys",
	"Flying Squirrels",
	"Fossas",
	"Foxs",
	"Fox Terriers",
	"French Bulldogs",
	"Frigatebirds",
	"Frilled Lizards",
	"Frogs",
	"Fur Seals",
	"Galapagos Penguins",
	"Galapagos Tortoises",
	"Gars",
	"Geckos",
	"Gentoo Penguins",
	"Geoffroys Tamarins",
	"Gerbils",
	"German Pinschers",
	"German Shepherds",
	"Gharials",
	"Giant African Land Snails",
	"Giant Clams",
	"Giant Panda Bears",
	"Giant Schnauzers",
	"Gibbons",
	"Gila Monsters",
	"Giraffes",
	"Glass Lizards",
	"Glow Worms",
	"Goats",
	"Golden Lion Tamarins",
	"Golden Orioles",
	"Golden Retrievers",
	"Gooses",
	"Gophers",
	"Gorillas",
	"Grasshoppers",
	"Great Danes",
	"Great White Sharks",
	"Greater Swiss Mountain Dogs",
	"Green Bee-Eaters",
	"Greenland Dogs",
	"Grey Mouse Lemurs",
	"Grey Reef Sharks",
	"Grey Seals",
	"Greyhounds",
	"Grizzly Bears",
	"Grouses",
	"Guinea Fowls",
	"Guinea Pigs",
	"Guppys",
	"Hammerhead Sharks",
	"Hamsters",
	"Hares",
	"Harriers",
	"Havaneses",
	"Hedgehogs",
	"Hercules Beetles",
	"Hermit Crabs",
	"Herons",
	"Highland Cattles",
	"Himalayans",
	"Hippopotamuss",
	"Honey Bees",
	"Horn Sharks",
	"Horned Frogs",
	"Horses",
	"Horseshoe Crabs",
	"Howler Monkeys",
	"Humans",
	"Humboldt Penguins",
	"Hummingbirds",
	"Humpback Whales",
	"Hyenas",
	"Ibiss",
	"Ibizan Hounds",
	"Iguanas",
	"Impalas",
	"Indian Elephants",
	"Indian Palm Squirrels",
	"Indian Rhinoceross",
	"Indian Star Tortoises",
	"Indochinese Tigers",
	"Indris",
	"Insects",
	"Irish Setters",
	"Irish WolfHounds",
	"Jack Russels",
	"Jackals",
	"Jaguars",
	"Japanese Chins",
	"Japanese Macaques",
	"Javan Rhinoceross",
	"Javaneses",
	"Jellyfishs",
	"Kakapos",
	"Kangaroos",
	"Keel Billed Toucans",
	"Killer Whales",
	"King Crabs",
	"King Penguins",
	"Kingfishers",
	"Kiwis",
	"Koalas",
	"Komodo Dragons",
	"Kudus",
	"Labradoodles",
	"Labrador Retrievers",
	"Ladybirds",
	"Leaf-Tailed Geckos",
	"Lemmings",
	"Lemurs",
	"Leopards",
	"Leopard Cats",
	"Leopard Seals",
	"Leopard Tortoises",
	"Ligers",
	"Lions",
	"Lionfishs",
	"Little Penguins",
	"Lizards",
	"Llamas",
	"Lobsters",
	"Long-Eared Owls",
	"Lynxs",
	"Macaroni Penguins",
	"Macaws",
	"Magellanic Penguins",
	"Magpies",
	"Maine Coons",
	"Malayan Civets",
	"Malayan Tigers",
	"Malteses",
	"Manatees",
	"Mandrills",
	"Manta Rays",
	"Marine Toads",
	"Markhors",
	"Marsh Frogs",
	"Masked Palm Civets",
	"Mastiffs",
	"Mayflys",
	"Meerkats",
	"Millipedes",
	"Minke Whales",
	"Moles",
	"Mollys",
	"Mongooses",
	"Mongrels",
	"Monitor Lizards",
	"Monkeys",
	"Monte Iberia Eleuths",
	"Moorhens",
	"Mooses",
	"Moray Eels",
	"Moths",
	"Mountain Gorillas",
	"Mountain Lions",
	"Mouses",
	"Mules",
	"Neanderthals",
	"Neapolitan Mastiffs",
	"Newfoundlands",
	"Newts",
	"Nightingales",
	"Norfolk Terriers",
	"Norwegian Forests",
	"Numbats",
	"Nurse Sharks",
	"Ocelots",
	"Octopuss",
	"Okapis",
	"Old English Sheepdogs",
	"Olms",
	"Opossums",
	"Orang-utans",
	"Ostrichs",
	"Otters",
	"Oysters",
	"Pademelons",
	"Panthers",
	"Parrots",
	"Patas Monkeys",
	"Peacocks",
	"Pekingeses",
	"Pelicans",
	"Penguins",
	"Persians",
	"Pheasants",
	"Pied Tamarins",
	"Pigs",
	"Pikas",
	"Pikes",
	"Pink Fairy Armadillos",
	"Piranhas",
	"Platypuss",
	"Pointers",
	"Poison Dart Frogs",
	"Polar Bears",
	"Pond Skaters",
	"Poodles",
	"Pool Frogs",
	"Porcupines",
	"Possums",
	"Prawns",
	"Proboscis Monkeys",
	"Puffer Fishs",
	"Puffins",
	"Pugs",
	"Pumas",
	"Purple Emperors",
	"Puss Moths",
	"Pygmy Hippopotamuss",
	"Pygmy Marmosets",
	"Quails",
	"Quetzals",
	"Quokkas",
	"Quolls",
	"Rabbits",
	"Raccoons",
	"Raccoon Dogs",
	"Radiated Tortoises",
	"Ragdolls",
	"Rats",
	"Rattlesnakes",
	"Red Knee Tarantulas",
	"Red Pandas",
	"Red Wolfs",
	"Red-handed Tamarins",
	"Reindeers",
	"Rhinoceross",
	"River Dolphins",
	"River Turtles",
	"Robins",
	"Rock Hyraxs",
	"Rockhopper Penguins",
	"Roseate Spoonbills",
	"Rottweilers",
	"Royal Penguins",
	"Russian Blues",
	"Sabre-Toothed Tigers",
	"Saint Bernards",
	"Salamanders",
	"Sand Lizards",
	"Saolas",
	"Scorpions",
	"Scorpion Fishs",
	"Sea Dragons",
	"Sea Lions",
	"Sea Otters",
	"Sea Slugs",
	"Sea Squirts",
	"Sea Turtles",
	"Sea Urchins",
	"Seahorses",
	"Seals",
	"Servals",
	"Sheeps",
	"Shih Tzus",
	"Shrimps",
	"Siameses",
	"Siamese Fighting Fishs",
	"Siberians",
	"Siberian Huskys",
	"Siberian Tigers",
	"Silver Dollars",
	"Skunks",
	"Sloths",
	"Slow Worms",
	"Snails",
	"Snakes",
	"Snapping Turtles",
	"Snowshoes",
	"Snowy Owls",
	"Somalis",
	"South China Tigers",
	"Spadefoot Toads",
	"Sparrows",
	"Spectacled Bears",
	"Sperm Whales",
	"Spider Monkeys",
	"Spiny Dogfishs",
	"Sponges",
	"Squids",
	"Squirrels",
	"Squirrel Monkeys",
	"Sri Lankan Elephants",
	"Staffordshire Bull Terriers",
	"Stag Beetles",
	"Starfishs",
	"Stellers Sea Cows",
	"Stick Insects",
	"Stingrays",
	"Stoats",
	"Striped Rocket Frogs",
	"Sumatran Elephants",
	"Sumatran Orang-utans",
	"Sumatran Rhinoceross",
	"Sumatran Tigers",
	"Sun Bears",
	"Swans",
	"Tangs",
	"Tapirs",
	"Tarsiers",
	"Tasmanian Devils",
	"Tawny Owls",
	"Termites",
	"Tetras",
	"Thorny Devils",
	"Tibetan Mastiffs",
	"Tiffanys",
	"Tigers",
	"Tiger Salamanders",
	"Tiger Sharks",
	"Tortoises",
	"Toucans",
	"Tree Frogs",
	"Tropicbirds",
	"Tuataras",
	"Turkeys",
	"Turkish Angoras",
	"Uakaris",
	"Uguisus",
	"Umbrellabirds",
	"Vampire Bats",
	"Vervet Monkeys",
	"Vultures",
	"Wallabys",
	"Walruss",
	"Warthogs",
	"Wasps",
	"Water Buffalos",
	"Water Dragons",
	"Water Voles",
	"Weasels",
	"Welsh Corgis",
	"West Highland Terriers",
	"Western Gorillas",
	"Western Lowland Gorillas",
	"Whale Sharks",
	"Whippets",
	"White Faced Capuchins",
	"White Rhinoceross",
	"White Tigers",
	"Wild Boars",
	"Wildebeests",
	"Wolfs",
	"Wolverines",
	"Wombats",
	"Woodlouses",
	"Woodpeckers",
	"Woolly Mammoths",
	"Woolly Monkeys",
	"Wrasses",
	"X-Ray Tetras",
	"Yals",
	"Yellow-Eyed Penguins",
	"Yorkshire Terriers",
	"Zebras",
	"Zebra Sharks",
	"Zebus",
	"Zonkeys",
	"Zorses",
]